services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123!"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  apiconnectorcore:
    image: apiconnectorcore
    build:
      context: .
      dockerfile: APIConnectorCore/Dockerfile
    ports:
      - "7163:8080"
    depends_on:
      - sqlserver

  prog7311part2:
    image: prog7311part2
    build:
      context: .
      dockerfile: Prog7311 Part2/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - apiconnectorcore

volumes:
  sqlserver_data: